---
ip: "192.168.10.10"
memory: 1048
cpus: 1
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: C:/Code
      to: /home/vagrant/Code

sites:
    - map: homestead.app
      to: /home/vagrant/Code/Laravel/public
    - map: circe.app
      to: /home/vagrant/Code/circe/public
    - map: gv1tr.app
      to: /home/vagrant/Code/gv1tr

# It looks like this is the file that actually gets used.

databases:
    - homestead

variables:
    - key: APP_ENV
      value: local

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar
